/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivacyDothtmlRouteImport } from './routes/privacy[.]html'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TermsDothtmlRouteImport } from './routes/terms[.]html'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyDothtmlRoute = PrivacyDothtmlRouteImport.update({
  id: '/privacy.html',
  path: '/privacy.html',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsDothtmlRoute = TermsDothtmlRouteImport.update({
  id: '/terms.html',
  path: '/terms.html',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/privacy.html': typeof PrivacyDothtmlRoute
  '/terms': typeof TermsRoute
  '/terms.html': typeof TermsDothtmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/privacy.html': typeof PrivacyDothtmlRoute
  '/terms': typeof TermsRoute
  '/terms.html': typeof TermsDothtmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/privacy.html': typeof PrivacyDothtmlRoute
  '/terms': typeof TermsRoute
  '/terms.html': typeof TermsDothtmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/privacy' | '/privacy.html' | '/terms' | '/terms.html'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/privacy' | '/privacy.html' | '/terms' | '/terms.html'
  id: '__root__' | '/' | '/privacy' | '/privacy.html' | '/terms' | '/terms.html'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyDothtmlRoute: typeof PrivacyDothtmlRoute
  TermsRoute: typeof TermsRoute
  TermsDothtmlRoute: typeof TermsDothtmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy.html': {
      id: '/privacy.html'
      path: '/privacy.html'
      fullPath: '/privacy.html'
      preLoaderRoute: typeof PrivacyDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms.html': {
      id: '/terms.html'
      path: '/terms.html'
      fullPath: '/terms.html'
      preLoaderRoute: typeof TermsDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyDothtmlRoute: PrivacyDothtmlRoute,
  TermsRoute: TermsRoute,
  TermsDothtmlRoute: TermsDothtmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
